# Generated by Django 3.2.4 on 2022-01-10 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0004_video_modulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curso.curso', verbose_name='Curso'),
        ),
    ]
