# Generated by Django 3.2.4 on 2022-01-10 17:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curso', '0010_anexovideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='usuarios_com_acesso',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='Usuários com acesso'),
        ),
    ]
