# Generated by Django 3.2.4 on 2022-01-10 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0012_comentario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'verbose_name': 'Comentário - Vídeo', 'verbose_name_plural': 'Comentários - Vídeos'},
        ),
    ]
