# Generated by Django 3.2.4 on 2022-02-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0023_auto_20220216_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='foto_grande/', verbose_name='Foto Grande'),
        ),
    ]
