# Generated by Django 3.2.4 on 2022-02-17 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0025_alter_video_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Aula', 'verbose_name_plural': 'Aulas'},
        ),
    ]
