# Generated by Django 3.2.4 on 2022-02-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0025_alter_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='foto_capa',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Foto de capa'),
        ),
    ]
