# Generated by Django 3.2.4 on 2022-02-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0030_alter_curso_pre_requisito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='pre_requisito',
            field=models.ManyToManyField(blank=True, null=True, to='curso.Curso', verbose_name='Pré-requisitos'),
        ),
    ]
