# Generated by Django 3.2.4 on 2022-02-21 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0033_auto_20220221_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curso.curso', verbose_name='Módulo'),
        ),
        migrations.AlterField(
            model_name='video',
            name='modulo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curso.modulo', verbose_name='Capítulo'),
        ),
    ]
