# Generated by Django 3.2.4 on 2022-07-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0037_modulo_linguagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulo',
            name='linguagem',
        ),
        migrations.AddField(
            model_name='curso',
            name='linguagem',
            field=models.CharField(choices=[('PT', 'PT'), ('ES', 'ES'), ('EN', 'EN')], default='PT', max_length=7, verbose_name='Linguagem'),
        ),
    ]
