# Generated by Django 3.2.4 on 2022-07-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0039_registrocapitulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrocapitulo',
            name='tipo',
            field=models.CharField(choices=[('Progresso nas vídeo-aulas', 'Progresso nas vídeo-aulas'), ('Progresso no Quizz', 'Progresso no Quizz')], default='Progresso nas vídeo-aulas', max_length=100, null=True, verbose_name='Tipo de Registro'),
        ),
    ]
