# Generated by Django 3.2.4 on 2022-07-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0041_alter_registrocapitulo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrocapitulo',
            name='tipo',
            field=models.CharField(choices=[('Progresso nas Videoaulas', 'Progresso nas Videoaulas'), ('Progresso no Quizz', 'Progresso no Quizz')], default='Progresso nas Videoaulas', max_length=100, null=True, verbose_name='Tipo de Registro'),
        ),
    ]
