# Generated by Django 3.2.4 on 2022-07-27 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0042_alter_registrocapitulo_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrocapitulo',
            name='modulo',
        ),
    ]
