# Generated by Django 3.2.4 on 2022-07-27 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0043_remove_registrocapitulo_modulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocapitulo',
            name='modulo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curso.curso', verbose_name='Modulo'),
        ),
    ]
