# Generated by Django 3.2.4 on 2022-02-04 12:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dicas_oportunidades', '0002_auto_20220204_0922'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DicasDirecionada',
            new_name='DicaDirecionada',
        ),
        migrations.RenameModel(
            old_name='DicasOportunidade',
            new_name='DicaOportunidade',
        ),
    ]
