# Generated by Django 3.2.4 on 2022-02-04 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dicas_oportunidades', '0003_auto_20220204_0934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dicadirecionada',
            options={'verbose_name': 'Dica direcionada', 'verbose_name_plural': 'Dicas direcionadas'},
        ),
        migrations.AlterModelOptions(
            name='dicaoportunidade',
            options={'verbose_name': 'Dica e oportunidade', 'verbose_name_plural': 'Dicas e oportunidades'},
        ),
    ]
