# Generated by Django 3.2.4 on 2022-02-04 13:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dicas_oportunidades', '0004_auto_20220204_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicadirecionada',
            name='lido_por',
            field=models.ManyToManyField(blank=True, related_name='lido', to=settings.AUTH_USER_MODEL, verbose_name='Lido por'),
        ),
        migrations.AlterField(
            model_name='dicadirecionada',
            name='usuarios_direcionados',
            field=models.ManyToManyField(blank=True, related_name='direcionados', to=settings.AUTH_USER_MODEL, verbose_name='Usuários direcionados'),
        ),
    ]
