# Generated by Django 3.2.4 on 2022-02-15 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0001_initial'),
        ('dicas_oportunidades', '0005_auto_20220204_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dicaoportunidade',
            old_name='descricao',
            new_name='dica',
        ),
        migrations.AddField(
            model_name='dicaoportunidade',
            name='pergunta_multipla_escolha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='perguntas.perguntamultiplaescolha', verbose_name='Pergunta multipla escolha'),
        ),
        migrations.AddField(
            model_name='dicaoportunidade',
            name='pergunta_objetiva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='perguntas.perguntaobjetiva', verbose_name='Pergunta objetiva'),
        ),
        migrations.DeleteModel(
            name='DicaDirecionada',
        ),
    ]
