# Generated by Django 3.2.4 on 2022-07-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_fabricante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espanhol', models.CharField(max_length=1000, null=True, verbose_name='Español')),
                ('portugues', models.CharField(max_length=1000, null=True, unique=True, verbose_name='Português')),
                ('ingles', models.CharField(max_length=1000, null=True, verbose_name='English')),
            ],
            options={
                'verbose_name': 'Tradução',
                'verbose_name_plural': 'Traduções',
            },
        ),
    ]
