# Generated by Django 3.2.4 on 2022-07-28 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0045_registrocapitulo_video'),
        ('core', '0004_traducao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linguagem', models.CharField(choices=[('PT', 'Portugues'), ('EN', 'Ingles'), ('ES', 'Espanhol')], max_length=100)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.video', verbose_name='Video')),
            ],
            options={
                'verbose_name': 'Instrucao',
                'verbose_name_plural': 'Instrucoes',
            },
        ),
    ]
