# Generated by Django 3.2.4 on 2022-07-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_instrucao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrucao',
            name='linguagem',
            field=models.CharField(choices=[('PT', 'PT'), ('EN', 'EN'), ('ES', 'ES')], default='PT', max_length=100),
        ),
        migrations.AlterField(
            model_name='instrucao',
            name='video',
            field=models.FileField(null=True, upload_to='video_instrucoes/', verbose_name='Video'),
        ),
    ]
