# Generated by Django 3.2.4 on 2022-08-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220728_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pontuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontuacao_bronze', models.FloatField(default=33.3, verbose_name='Pontuação Bronze')),
                ('pontuacao_prata', models.FloatField(default=66.6, verbose_name='Pontuação prata')),
                ('pontuacao_ouro', models.FloatField(default=80.0, verbose_name='Pontuação Ouro')),
            ],
            options={
                'verbose_name': 'Pontuação',
                'verbose_name_plural': 'Pontuações',
            },
        ),
    ]
