# Generated by Django 3.2.4 on 2022-01-10 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='modulo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curso.modulo', verbose_name='Módulo'),
        ),
    ]
