# Generated by Django 3.2.4 on 2022-02-04 13:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curso', '0015_anexovideo_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='usuarios_com_acesso',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Usuários com acesso'),
        ),
        migrations.AlterField(
            model_name='video',
            name='usuarios_concluintes',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Usuários concluintes'),
        ),
    ]
