# Generated by Django 3.2.4 on 2022-02-09 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0019_comentario_resposta_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='resposta_comentario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resposta_comentario_set', to='curso.comentario', verbose_name='Resposta para o comentário'),
        ),
    ]
