# Generated by Django 3.2.4 on 2022-02-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0020_alter_comentario_resposta_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='foto_grande',
            field=models.ImageField(null=True, upload_to='Foto Grande', verbose_name='Foto Pequena'),
        ),
        migrations.AddField(
            model_name='video',
            name='foto_pequena',
            field=models.ImageField(null=True, upload_to='Foto Pequena', verbose_name='Foto Pequena'),
        ),
    ]
