# Generated by Django 3.2.4 on 2022-02-16 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0022_alter_video_foto_grande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='foto_grande',
        ),
        migrations.RemoveField(
            model_name='video',
            name='foto_pequena',
        ),
    ]
