# Generated by Django 3.2.4 on 2022-02-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0025_alter_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='pre_requisito',
            field=models.ManyToManyField(to='curso.Curso', verbose_name='Pré-requisito'),
        ),
    ]
