# Generated by Django 3.2.4 on 2022-02-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0026_curso_pre_requisito'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='progresso_minimo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Progresso mínimo'),
        ),
        migrations.AddField(
            model_name='curso',
            name='score_minimo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Score mínimo'),
        ),
    ]
