# Generated by Django 3.2.4 on 2022-02-17 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0026_curso_foto_capa'),
        ('curso', '0027_auto_20220217_1029'),
    ]

    operations = [
    ]
