# Generated by Django 3.2.4 on 2022-02-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0031_alter_curso_pre_requisito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='progresso_minimo',
            field=models.IntegerField(blank=True, default=90, null=True, verbose_name='Progresso mínimo'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='score_minimo',
            field=models.IntegerField(blank=True, default=75, null=True, verbose_name='Score mínimo'),
        ),
    ]
