# Generated by Django 3.2.4 on 2022-02-21 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0032_auto_20220218_1528'),
        ('curso', '0034_auto_20220221_0735'),
    ]

    operations = [
    ]
