# Generated by Django 3.2.4 on 2022-07-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0036_alter_curso_foto_capa'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='linguagem',
            field=models.CharField(choices=[('PT', 'PT'), ('ES', 'ES'), ('EN', 'EN')], default='PT', max_length=7, verbose_name='Linguagem'),
        ),
    ]
