# Generated by Django 3.2.4 on 2022-07-27 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curso', '0038_auto_20220725_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroCapitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Progresso no Capitulo', 'Progresso no Capitulo')], default='Progresso no Capitulo', max_length=100, null=True, verbose_name='Tipo de Registro')),
                ('data_hora', models.DateTimeField(verbose_name='Data e Hora')),
                ('progresso', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Progresso no Capitulo')),
                ('modulo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curso.modulo', verbose_name='Capitulo')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Registro do Capitulo',
                'verbose_name_plural': 'Registros dos Capitulos',
            },
        ),
    ]
