# Generated by Django 3.2.4 on 2022-07-27 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0044_registrocapitulo_modulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocapitulo',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curso.video', verbose_name='Videoaula'),
        ),
    ]
