# Generated by Django 3.2.4 on 2022-07-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0045_registrocapitulo_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='icone',
            field=models.CharField(blank=True, help_text='Copie e cole um ícone da <a target="_blank" href="https://ionic.io/ionicons">ionicons</a> ou <a target="_blank" href="https://fontawesome.com/v4/icons/">Font Awesome 4</a>', max_length=70, null=True, verbose_name='ícone'),
        ),
    ]
