# Generated by Django 3.2.4 on 2022-08-23 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curso', '0046_modulo_icone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Campo Obrigatório', max_length=250, verbose_name='Título')),
                ('linguagem', models.CharField(choices=[('PT', 'PT'), ('ES', 'ES'), ('EN', 'EN')], default='PT', max_length=7, verbose_name='Linguagem')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('foto_capa', models.ImageField(blank=True, help_text='Resolução sugerida 320 x 450', null=True, upload_to='', verbose_name='Foto de capa')),
                ('data_alteracao', models.DateTimeField(auto_now=True, verbose_name='Data de Alteração')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('usuario_atualizacao', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projeto_requests_modified', to=settings.AUTH_USER_MODEL)),
                ('usuario_criacao', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projeto_requests_created', to=settings.AUTH_USER_MODEL)),
                ('usuarios_com_acesso', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Usuários com acesso')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='projeto_relacionado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curso.projeto'),
        ),
    ]
