# Generated by Django 3.2.4 on 2022-08-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0048_auto_20220808_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulo',
            name='pontuacao_bronze',
        ),
        migrations.RemoveField(
            model_name='modulo',
            name='pontuacao_ouro',
        ),
        migrations.RemoveField(
            model_name='modulo',
            name='pontuacao_prata',
        ),
        migrations.AddField(
            model_name='curso',
            name='pontuacao_bronze',
            field=models.FloatField(default=33.3, verbose_name='Pontuação Bronze'),
        ),
        migrations.AddField(
            model_name='curso',
            name='pontuacao_ouro',
            field=models.FloatField(default=80.0, verbose_name='Pontuação Ouro'),
        ),
        migrations.AddField(
            model_name='curso',
            name='pontuacao_prata',
            field=models.FloatField(default=66.6, verbose_name='Pontuação prata'),
        ),
    ]
