# Generated by Django 3.2.4 on 2022-09-12 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0050_auto_20220901_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='projeto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curso.projeto'),
        ),
    ]
