# Generated by Django 3.2.4 on 2022-09-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pontuacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontuacao',
            name='pontuacao_ouro',
            field=models.FloatField(default=66.7, verbose_name='Pontuação Ouro'),
        ),
    ]
