# Generated by Django 3.2.4 on 2022-01-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0005_modulo_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='ordem',
            field=models.IntegerField(default=1, null=True, verbose_name='Ordem'),
        ),
        migrations.AddField(
            model_name='video',
            name='ordem',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Ordem'),
        ),
    ]
