# Generated by Django 3.2.4 on 2022-01-10 17:14

import curso.models.video
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0008_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(help_text='Campo Obrigatório', upload_to='video/', validators=[curso.models.video.Video.validate_file_extension], verbose_name='Vídeo'),
        ),
    ]
