# Generated by Django 3.2.4 on 2022-02-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0014_video_usuarios_concluintes'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexovideo',
            name='titulo',
            field=models.CharField(default=2, max_length=200, verbose_name='titulo'),
            preserve_default=False,
        ),
    ]
