# Generated by Django 3.2.4 on 2022-02-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0016_auto_20220204_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='nota',
            field=models.IntegerField(verbose_name='Nota'),
        ),
    ]
