# Generated by Django 3.2.4 on 2022-02-08 09:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0017_alter_avaliacao_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='nota',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'A nota deve ser maior que 0'), django.core.validators.MaxValueValidator(5, 'A nota deve ser menor ou igual a 5')], verbose_name='Nota'),
        ),
    ]
