# Generated by Django 3.2.4 on 2022-02-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0021_auto_20220216_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='foto_grande',
            field=models.ImageField(null=True, upload_to='Foto Grande', verbose_name='Foto Grande'),
        ),
    ]
