# Generated by Django 3.2.4 on 2022-02-17 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0026_alter_video_options'),
        ('curso', '0028_merge_0026_curso_foto_capa_0027_auto_20220217_1029'),
    ]

    operations = [
    ]
