# Generated by Django 3.2.4 on 2022-02-21 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0032_auto_20220218_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name': 'Módulo', 'verbose_name_plural': 'Módulos'},
        ),
        migrations.AlterModelOptions(
            name='modulo',
            options={'verbose_name': 'Capítulo', 'verbose_name_plural': 'Capítulos'},
        ),
    ]
