# Generated by Django 3.2.4 on 2022-06-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0035_merge_0032_auto_20220218_1528_0034_auto_20220221_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='foto_capa',
            field=models.ImageField(blank=True, help_text='Resolução sugerida 320 x 450', null=True, upload_to='', verbose_name='Foto de capa'),
        ),
    ]
