# Generated by Django 3.2.4 on 2022-02-03 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0015_anexovideo_titulo'),
        ('assessment', '0004_delete_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='modulo',
            field=models.ForeignKey(blank=True, help_text='Módulo ao qual o assessment pertence', null=True, on_delete=django.db.models.deletion.CASCADE, to='curso.modulo', verbose_name='Módulo'),
        ),
    ]
