# Generated by Django 3.2.4 on 2022-02-11 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0008_delete_etapa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perguntaobjetiva',
            name='alternativa_correta',
        ),
        migrations.RemoveField(
            model_name='perguntaobjetiva',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='perguntaobjetiva',
            name='resposta',
        ),
        migrations.RemoveField(
            model_name='perguntaobjetiva',
            name='usuario_atualizacao',
        ),
        migrations.RemoveField(
            model_name='perguntaobjetiva',
            name='usuario_criacao',
        ),
        migrations.RemoveField(
            model_name='perguntaobjetiva',
            name='usuarios_responderam',
        ),
    ]
