# Generated by Django 3.2.4 on 2022-02-18 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0003_auto_20220218_1037'),
        ('assessment', '0010_auto_20220211_1237'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alternativa',
        ),
    ]
