# Generated by Django 3.2.4 on 2022-07-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0011_delete_alternativa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fabricante', models.CharField(max_length=255, verbose_name='Nome do Fabricante')),
                ('nome_auth', models.CharField(max_length=255, verbose_name='Nome no Auth')),
                ('linguagem', models.CharField(choices=[('PT', 'PT'), ('ES', 'ES'), ('EN', 'EN')], default='PT', max_length=7, null=True, verbose_name='Linguagem')),
            ],
            options={
                'verbose_name': 'Fabricante',
                'verbose_name_plural': 'Fabricantes',
                'ordering': ('nome_fabricante', 'id'),
            },
        ),
    ]
