# Generated by Django 3.2.4 on 2022-07-25 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0012_fabricante'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fabricante',
        ),
    ]
