# Generated by Django 3.2.9 on 2021-12-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinetics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kinetics',
            options={'verbose_name': 'Kinetics', 'verbose_name_plural': 'Kinetics'},
        ),
        migrations.AddField(
            model_name='kinetics',
            name='project_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kinetics',
            name='project_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kinetics',
            name='secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kinetics',
            name='url_api',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kinetics',
            name='url_base',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kinetics',
            name='url_redirect',
            field=models.URLField(blank=True, null=True),
        ),
    ]
