# Generated by Django 3.2.9 on 2021-12-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinetics', '0002_auto_20211221_1428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kinetics',
            options={'verbose_name': 'Cinética', 'verbose_name_plural': 'Cinética'},
        ),
        migrations.AlterField(
            model_name='kinetics',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='kinetics',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='kinetics',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='kinetics',
            name='project_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='id do projeto'),
        ),
        migrations.AlterField(
            model_name='kinetics',
            name='project_url',
            field=models.URLField(blank=True, null=True, verbose_name='url do projeto'),
        ),
        migrations.AlterField(
            model_name='kinetics',
            name='secret',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='segredo'),
        ),
        migrations.AlterField(
            model_name='kinetics',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
        migrations.AlterField(
            model_name='kinetics',
            name='url_api',
            field=models.URLField(blank=True, null=True, verbose_name='url_api'),
        ),
        migrations.AlterField(
            model_name='kinetics',
            name='url_base',
            field=models.URLField(blank=True, null=True, verbose_name='base de url'),
        ),
        migrations.AlterField(
            model_name='kinetics',
            name='url_redirect',
            field=models.URLField(blank=True, null=True, verbose_name='url_redirect'),
        ),
    ]
