# Generated by Django 3.2.9 on 2021-12-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinetics', '0003_auto_20211227_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kinetics',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='kinetics',
            name='project_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Id do projeto'),
        ),
        migrations.AlterField(
            model_name='kinetics',
            name='secret',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SSegredo'),
        ),
        migrations.AlterField(
            model_name='kinetics',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
    ]
