# Generated by Django 3.2.9 on 2022-01-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinetics', '0005_merge_0003_auto_20211227_1543_0004_auto_20211228_1256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kinetics',
            options={'verbose_name': 'Kinetics', 'verbose_name_plural': 'Kinetics'},
        ),
        migrations.AlterField(
            model_name='kinetics',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='kinetics',
            name='project_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Id do projeto'),
        ),
        migrations.AlterField(
            model_name='kinetics',
            name='project_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL do projeto'),
        ),
        migrations.AlterField(
            model_name='kinetics',
            name='secret',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Secret'),
        ),
        migrations.AlterField(
            model_name='kinetics',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='kinetics',
            name='url_api',
            field=models.URLField(blank=True, null=True, verbose_name='URL da API'),
        ),
        migrations.AlterField(
            model_name='kinetics',
            name='url_base',
            field=models.URLField(blank=True, null=True, verbose_name='URL Base'),
        ),
        migrations.AlterField(
            model_name='kinetics',
            name='url_redirect',
            field=models.URLField(blank=True, null=True, verbose_name='URL de Redirect'),
        ),
    ]
