# Generated by Django 3.2.4 on 2022-08-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respostas', '0002_alter_resposta_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='resposta',
            name='apta_refazer',
            field=models.BooleanField(default=False, verbose_name='Apta a refazer'),
        ),
    ]
