# Generated by Django 3.2.4 on 2022-02-11 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0006_auto_20220204_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anexo',
            name='etapa',
        ),
        migrations.RemoveField(
            model_name='perguntacheck',
            name='etapa',
        ),
        migrations.RemoveField(
            model_name='perguntadiscursiva',
            name='etapa',
        ),
        migrations.RemoveField(
            model_name='perguntaobjetiva',
            name='etapa',
        ),
        migrations.AddField(
            model_name='anexo',
            name='assessment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessment.assessment', verbose_name='Assessment'),
        ),
        migrations.AddField(
            model_name='perguntacheck',
            name='assessment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessment.assessment', verbose_name='Assessment'),
        ),
        migrations.AddField(
            model_name='perguntadiscursiva',
            name='assessment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessment.assessment', verbose_name='Assessment'),
        ),
        migrations.AddField(
            model_name='perguntaobjetiva',
            name='assessment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessment.assessment', verbose_name='Assessment'),
        ),
    ]
