# Generated by Django 3.2.4 on 2022-02-11 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0007_auto_20220211_0930'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Etapa',
        ),
    ]
