# Generated by Django 3.2.4 on 2022-02-11 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0009_auto_20220211_1237'),
        ('perguntas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternativa',
            name='pergunta_multipla_escolha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='perguntas.perguntamultiplaescolha', verbose_name='Pergunta de múltipla escolha'),
        ),
        migrations.AddField(
            model_name='alternativa',
            name='valor',
            field=models.IntegerField(default=0, help_text='Necessário somente se a pergunta for de múltipla escolha', verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='alternativa',
            name='data_alteracao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de alteração'),
        ),
        migrations.AlterField(
            model_name='alternativa',
            name='pergunta_objetiva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='perguntas.perguntaobjetiva', verbose_name='Pergunta Objetiva'),
        ),
        migrations.AlterField(
            model_name='alternativa',
            name='titulo',
            field=models.CharField(max_length=250, verbose_name='Título'),
        ),
        migrations.DeleteModel(
            name='PerguntaObjetiva',
        ),
    ]
