# Generated by Django 3.2.4 on 2022-02-09 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kinetics', '0006_auto_20220103_0935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kinetics',
            options={'verbose_name': 'Kinetic', 'verbose_name_plural': 'Kinetics'},
        ),
    ]
