# Generated by Django 3.2.9 on 2022-01-03 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kinetics', '0003_auto_20211227_1543'),
        ('kinetics', '0004_auto_20211228_1256'),
    ]

    operations = [
    ]
