# Generated by Django 3.2.4 on 2022-02-18 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perguntas', '0002_perguntamultiplaescolha_contem_mais_de_uma_resposta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('valor', models.IntegerField(default=0, help_text='Necessário somente se a pergunta for de múltipla escolha', verbose_name='Valor')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_alteracao', models.DateTimeField(auto_now=True, verbose_name='Data de alteração')),
                ('pergunta_multipla_escolha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='perguntas.perguntamultiplaescolha', verbose_name='Pergunta de múltipla escolha')),
                ('pergunta_objetiva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='perguntas.perguntaobjetiva', verbose_name='Pergunta Objetiva')),
                ('usuario_atualizacao', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alternativa_requests_modified', to=settings.AUTH_USER_MODEL)),
                ('usuario_criacao', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alternativa_requests_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alternativa',
                'verbose_name_plural': 'Alternativas',
            },
        ),
        migrations.AlterField(
            model_name='perguntaobjetiva',
            name='alternativa_correta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='perguntas.alternativa', verbose_name='Alternativa correta'),
        ),
    ]
