# Generated by Django 3.2.4 on 2022-08-01 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0047_auto_20220801_0906'),
        ('perguntas', '0003_auto_20220218_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='perguntamultiplaescolha',
            name='aula_relacionada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curso.video', verbose_name='Aula Relacionada'),
        ),
    ]
