# Generated by Django 3.2.4 on 2022-02-14 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perguntas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(max_length=255, verbose_name='Resposta')),
                ('pontuacao', models.IntegerField(default=0, verbose_name='Pontuação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('pergunta_multipla_escolha', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='perguntas.perguntamultiplaescolha', verbose_name='Pergunta multipla escolha')),
                ('pergunta_objetiva', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='perguntas.perguntaobjetiva', verbose_name='Pergunta objetiva')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('usuario_atualizacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_atualizacao', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de atualização')),
            ],
            options={
                'verbose_name': 'resposta',
                'verbose_name_plural': 'Respostas',
            },
        ),
    ]
