# Generated by Django 3.2.4 on 2022-02-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicas_oportunidades', '0006_auto_20220215_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicaoportunidade',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data de atualização'),
        ),
        migrations.AddField(
            model_name='dicaoportunidade',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de criação'),
        ),
    ]
