# Generated by Django 3.2.4 on 2022-02-16 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0020_alter_comentario_resposta_comentario'),
        ('dicas_oportunidades', '0009_dicaoportunidade_aula_sugerida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicaoportunidade',
            name='aula_sugerida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curso.video', verbose_name='Aula sugerida'),
        ),
    ]
