# Generated by Django 3.2.4 on 2022-02-04 12:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dicas_oportunidades', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DicasDirecionadas',
            new_name='DicasDirecionada',
        ),
        migrations.RenameModel(
            old_name='DicasOportunidades',
            new_name='DicasOportunidade',
        ),
    ]
