# Generated by Django 3.2.4 on 2022-02-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicas_oportunidades', '0007_auto_20220215_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicaoportunidade',
            name='dica',
            field=models.TextField(null=True, verbose_name='Dica'),
        ),
    ]
