# Generated by Django 3.2.4 on 2022-02-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicas_oportunidades', '0008_alter_dicaoportunidade_dica'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicaoportunidade',
            name='aula_sugerida',
            field=models.URLField(blank=True, null=True, verbose_name='Aula sugerida'),
        ),
    ]
