# Generated by Django 3.2.4 on 2022-01-10 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
