# Generated by Django 3.2.4 on 2021-06-30 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoAlternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Campo Obrigatório', max_length=250, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('data_alteracao', models.DateTimeField(auto_now=True, verbose_name='Data de Alteração')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Configuração Alternativa',
                'verbose_name_plural': 'Configurações Alternativas',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Campo Obrigatório', max_length=250, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Decrição')),
                ('data_alteracao', models.DateTimeField(auto_now=True, verbose_name='Data de Alteração')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.empresa', verbose_name='Empresa')),
                ('grupos', models.ManyToManyField(blank=True, to='auth.Group', verbose_name='Grupos')),
                ('usuario_atualizacao', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracaoassessment_requests_modified', to=settings.AUTH_USER_MODEL)),
                ('usuario_criacao', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracaoassessment_requests_created', to=settings.AUTH_USER_MODEL)),
                ('usuarios', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Usuários')),
            ],
            options={
                'verbose_name': 'Configuração Assessment',
                'verbose_name_plural': 'Configurações Assessment',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Campo Obrigatório', max_length=250, verbose_name='Nome')),
                ('ordem', models.IntegerField(blank=True, default=1, null=True, verbose_name='Ordem')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('data_alteracao', models.DateTimeField(auto_now=True, verbose_name='Data de Alteração')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('configuracao_assessment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuracao_assessment.configuracaoassessment', verbose_name='Configuração Assessment')),
                ('usuario_atualizacao', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracaoetapa_requests_modified', to=settings.AUTH_USER_MODEL)),
                ('usuario_criacao', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracaoetapa_requests_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração Etapa',
                'verbose_name_plural': 'Configurações Etapas',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoPerguntaObjetiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Campo Obrigatório', max_length=250, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('data_alteracao', models.DateTimeField(auto_now=True, verbose_name='Data de Alteração')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('alternativa_correta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuracao_assessment.configuracaoalternativa', verbose_name='Alternativa Correta')),
                ('configuracao_etapa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuracao_assessment.configuracaoetapa', verbose_name='Configuração Etapa')),
                ('usuario_atualizacao', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracaoperguntaobjetiva_requests_modified', to=settings.AUTH_USER_MODEL)),
                ('usuario_criacao', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracaoperguntaobjetiva_requests_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração Pergunta Objetiva',
                'verbose_name_plural': 'Configurações Perguntas Objetivas',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoPerguntaDiscursiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Campo Obrigatório', max_length=250, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('data_alteracao', models.DateTimeField(auto_now=True, verbose_name='Data de Alteração')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('configuracao_etapa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuracao_assessment.configuracaoetapa', verbose_name='Configuração Etapa')),
                ('usuario_atualizacao', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracaoperguntadiscursiva_requests_modified', to=settings.AUTH_USER_MODEL)),
                ('usuario_criacao', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracaoperguntadiscursiva_requests_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração Pergunta Discursiva',
                'verbose_name_plural': 'Configurações Perguntas Discursivas',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoPerguntaCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Campo Obrigatório', max_length=250, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('resposta_esperada', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não')], default='NAO', max_length=10)),
                ('data_alteracao', models.DateTimeField(auto_now=True, verbose_name='Data de Alteração')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('configuracao_etapa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuracao_assessment.configuracaoetapa', verbose_name='Configuração Etapa')),
                ('usuario_atualizacao', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracaoperguntacheck_requests_modified', to=settings.AUTH_USER_MODEL)),
                ('usuario_criacao', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracaoperguntacheck_requests_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração Pergunta Check',
                'verbose_name_plural': 'Configurações Perguntas Check',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Campo Obrigatório', max_length=250, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('data_alteracao', models.DateTimeField(auto_now=True, verbose_name='Data de Alteração')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('configuracao_etapa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuracao_assessment.configuracaoetapa', verbose_name='Configuração Etapa')),
                ('usuario_atualizacao', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracaoanexo_requests_modified', to=settings.AUTH_USER_MODEL)),
                ('usuario_criacao', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracaoanexo_requests_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração Anexo',
                'verbose_name_plural': 'Configurações Anexos',
            },
        ),
        migrations.AddField(
            model_name='configuracaoalternativa',
            name='configuracao_pergunta_objetiva',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuracao_assessment.configuracaoperguntaobjetiva', verbose_name='Configuração pergunta objetiva'),
        ),
        migrations.AddField(
            model_name='configuracaoalternativa',
            name='usuario_atualizacao',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracaoalternativa_requests_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configuracaoalternativa',
            name='usuario_criacao',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracaoalternativa_requests_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
